[package]
name = "yek"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.3"
ignore = "0.4"
walkdir = "2.3"
sha2 = "0.10"
regex = "1.9"
anyhow = "1.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
