[package]
name = "yek"
version = "0.7.2"
edition = "2021"

[dependencies]
anyhow = "1.0"
byte-unit = "4.0"
clap = "4.4"
crossbeam = "0.8"
ignore = "0.4"
indicatif = "0.17"
num_cpus = "1.15"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
time = "0.3"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["time", "local-time"] }
walkdir = "2.4"

[dev-dependencies]
assert_cmd = "2.0"
chrono = "0.4"
predicates = "3.0"
tempfile = "3.9"
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "serialization"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
