[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v2"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=x86-64-v2"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-m1"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64-v2"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=generic"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-cpu=generic"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=generic"] 