name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short
  OPENSSL_STATIC: true
  PKG_CONFIG_ALLOW_CROSS: true

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Format check
        run: cargo fmt --check

  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy

      - name: Install OpenSSL (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openssl --params='/InstallationPath:C:\OpenSSL\'
          echo "OPENSSL_DIR=C:\OpenSSL" >> $env:GITHUB_ENV
          echo "PKG_CONFIG_PATH=C:\OpenSSL\lib\pkgconfig" >> $env:GITHUB_ENV

      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build ${{ matrix.target }}
    needs: [lint, test]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds using cross
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: yek-x86_64-unknown-linux-gnu.tar.gz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            asset_name: yek-aarch64-unknown-linux-gnu.tar.gz
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: yek-x86_64-unknown-linux-musl.tar.gz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            asset_name: yek-aarch64-unknown-linux-musl.tar.gz
          # Native macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: yek-x86_64-apple-darwin.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: yek-aarch64-apple-darwin.tar.gz
          # Native Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: yek-x86_64-pc-windows-msvc.zip
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            asset_name: yek-aarch64-pc-windows-msvc.zip

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        id: build
        with:
          target: ${{ matrix.target }}

      - name: Package binary (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p release-artifacts
          staging="yek-${{ matrix.target }}"
          mkdir -p "$staging"
          cp "${{ steps.build.outputs.binary_path }}" "$staging/"
          tar czf "release-artifacts/${{ matrix.asset_name }}" "$staging"
          # Verify the artifact exists and has size > 0
          if [ ! -f "release-artifacts/${{ matrix.asset_name }}" ]; then
            echo "::error::Packaged artifact not found: release-artifacts/${{ matrix.asset_name }}"
            exit 1
          fi
          if [ ! -s "release-artifacts/${{ matrix.asset_name }}" ]; then
            echo "::error::Packaged artifact is empty: release-artifacts/${{ matrix.asset_name }}"
            exit 1
          fi
          echo "Successfully packaged ${{ matrix.asset_name }}"
          ls -lh "release-artifacts/${{ matrix.asset_name }}"

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release-artifacts
          $staging = "yek-${{ matrix.target }}"
          New-Item -ItemType Directory -Force -Path $staging
          Copy-Item "${{ steps.build.outputs.binary_path }}" -Destination $staging
          7z a "release-artifacts\${{ matrix.asset_name }}" "$staging"
          # Verify the artifact exists and has size > 0
          if (-not (Test-Path "release-artifacts\${{ matrix.asset_name }}")) {
            Write-Error "Packaged artifact not found: release-artifacts\${{ matrix.asset_name }}"
            exit 1
          }
          $fileInfo = Get-Item "release-artifacts\${{ matrix.asset_name }}"
          if ($fileInfo.Length -eq 0) {
            Write-Error "Packaged artifact is empty: release-artifacts\${{ matrix.asset_name }}"
            exit 1
          }
          Write-Host "Successfully packaged ${{ matrix.asset_name }}"
          Get-Item "release-artifacts\${{ matrix.asset_name }}" | Select-Object Length,LastWriteTime

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: release-artifacts/${{ matrix.asset_name }}
          if-no-files-found: error

  stress:
    name: Stress ${{ matrix.target }}
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-stress-${{ matrix.target }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds using cross
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          # Native macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          # Native Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      # Download the binary from CI build
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: dist

      - name: Extract and install binary
        shell: bash
        run: |
          mkdir -p bin
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z x "dist/yek-${{ matrix.target }}.zip" -obin
            cp bin/yek-${{ matrix.target }}/yek.exe /c/Windows/System32/
          else
            tar xzf dist/yek-${{ matrix.target }}.tar.gz -C bin
            chmod +x bin/yek-${{ matrix.target }}/yek
            sudo cp bin/yek-${{ matrix.target }}/yek /usr/local/bin/
          fi

      - name: Checkout VSCode repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vscode
          path: vscode
          fetch-depth: 1

      - name: Run stress test
        shell: bash
        timeout-minutes: 1
        working-directory: vscode
        run: yek

  benchmark:
    name: Benchmark / ${{ matrix.benchmark_group.name }}
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-benchmark-${{ matrix.benchmark_group.group }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        benchmark_group:
          - group: SingleFile_ByteMode
            name: Single File Byte Mode
          - group: SingleFile_ByteMode_Large
            name: Single File Byte Mode Large
          - group: SingleFile_TokenMode_Large
            name: Single File Token Mode Large
          - group: MultipleFiles_Small
            name: Multiple Files Small
          - group: MultipleFiles_Medium
            name: Multiple Files Medium
          - group: MultipleFiles_Large
            name: Multiple Files Large
          - group: MultipleFiles_TokenMode
            name: Multiple Files Token Mode
          - group: CustomConfig
            name: Custom Config

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run benchmarks
        run: |
          # Build and run on target branch
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          cargo bench --bench serialization --no-run
          cargo bench --bench serialization -- --save-baseline ${{ github.base_ref }} '${{ matrix.benchmark_group.group }}/'

          # Build and compare on PR branch
          git checkout ${{ github.head_ref }}
          cargo bench --bench serialization --no-run
          cargo bench --bench serialization -- --baseline ${{ github.base_ref }} --noise-threshold 2 '${{ matrix.benchmark_group.group }}/' > benchmark_results.md
          echo "## Benchmark Results for ${{ matrix.benchmark_group.name }}" >> $GITHUB_STEP_SUMMARY
          cat benchmark_results.md >> $GITHUB_STEP_SUMMARY

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: criterion-${{ matrix.benchmark_group.group }}-results
          path: benchmark_results.md
          if-no-files-found: error

  release:
    name: Release
    needs: [test, lint, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      # Download all artifacts to a single directory
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: build-*

      - name: Generate release notes
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --current --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/build-*/yek-*
          body_path: CHANGES.md
          tag_name: ${{ github.ref_name }}

  publish:
    name: Publish to crates.io
    needs: [test, lint, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.84.0"
      - run: |
          # ensure version does not already exist
          if cargo search --color=never yek | grep -q ${{ github.ref_name }}; then
            echo "yek@${{ github.ref_name }} already published"
            exit 0
          fi
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
