name: Installation Test

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test-linux-install:
    name: Test Linux Installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get install script
        id: get_linux_install_script
        shell: bash
        run: |
          script=$(sed -n '/<!-- LINUX_INSTALLATION_BEGIN -->/,/<!-- LINUX_INSTALLATION_END -->/p' README.md | grep -v '^```')
          echo "script=$script" >> $GITHUB_OUTPUT

      - name: Test installation script
        run: ${{ steps.get_linux_install_script.outputs.script }}

      - name: Verify installation
        run: |
          yek --version
          # Create a test file
          echo "test content" > test.txt
          # Test basic functionality
          yek test.txt
          # Verify output exists
          test -f repo-serialized/chunk-0.txt

  test-windows-install:
    name: Test Windows Installation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get install script
        id: get_windows_install_script
        shell: bash
        run: |
          script=$(sed -n '/<!-- WINDOWS_INSTALLATION_BEGIN -->/,/<!-- WINDOWS_INSTALLATION_END -->/p' README.md | grep -v '^```')
          echo "script=$script" >> $GITHUB_OUTPUT

      - name: Test installation script
        shell: powershell
        run: ${{ steps.get_windows_install_script.outputs.script }}

      - name: Verify installation
        shell: powershell
        run: |
          yek --version
          # Create a test file
          "test content" | Out-File -FilePath test.txt
          # Test basic functionality
          yek test.txt
          # Verify output exists
          if (-not (Test-Path repo-serialized/chunk-0.txt)) {
            throw "Output file not found"
          }
